### ISSUE TITLE
タイトルをフォーカスインした状態で開始時間を変えるとクラッシュする

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#123]
■事象
下記の手順で画面が白くなる
1. Planを一つにする
2. title に文字を入れる
3. 開始時間をクリックする
4. 「変更」ボタンを押す

■エラーログ
`EditablePlan.jsx:34 Uncaught TypeError: Cannot read properties of undefined (reading 'title')
    at OG0006EditablePlan (EditablePlan.jsx:34:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)`
![CPT2208121437-450x623](https://user-images.githubusercontent.com/53715839/184291864-10d5b517-561d-43ba-adb9-02e172371ca4.gif)

**Comment by Ayato-kosaka** [comment]
@Takapy1 これお願いしていい？

**Comment by Takapy1** [comment]
@Ayato-kosaka 了解したー！

**Comment by Ayato-kosaka** [comment]
これ結構むずそうやな...
変更ボタン押す前に両方共 title は埋まってるけど、
なんで変更ボタン押したら Cannot read properties of undefined (reading 'title') になるんやろ
![image](https://user-images.githubusercontent.com/53715839/184298973-bd37aac6-6f77-4613-b17c-eb3b468c9dc5.png)

**Comment by Ayato-kosaka** [comment]
変更ボタン押したら、どこかのタイミングでcontext の plansから2番目のplanが消えてる、、、なんでだ？？
![image](https://user-images.githubusercontent.com/53715839/184300093-be627338-58f9-471e-b681-6eca22b05160.png)
