### ISSUE TITLE
アプリ開くとエラー

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#285]
@Ayato-kosaka 

アプリが開けない、何かわかれば教えて欲しい
```
Error: Component firestore has not been registered yet
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:40 in guardedLoadModule
at http://192.168.3.179:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
指摘修正中は開けてた？それともexpo起動せずに指摘修正してた？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
expo 開いてなかった

**Comment by Ayato-kosaka** [comment]
@Takapy1 じゃあ何かの修正でエラーになったってことだよね？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
その可能性が高いな
firestore.tsがエラー吐いてそうなんだよね、へんなものnpm installしてしまったのかな
```
Error: Requiring module "src/Place/Endpoint/firestore.ts", which threw an exception: Error: Component firestore has not been registered yet
at node_modules/expo/build/logs/LogSerialization.js:111:24 in stack.map$argument_0
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:41:6 in preprocessException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:78:19 in reportException
at node_modules/react-native/Libraries/Performance/Systrace.js:174:17 in beginAsyncEvent
at node_modules/expo-font/build/FontHooks.js:2:0 in <global>
at node_modules/expo-font/build/FontHooks.js:22:28 in useFonts
at node_modules/expo/build/environment/DevLoadingView.js:60:54 in DevLoadingView
at node_modules/react-native/Libraries/Core/Devtools/symbolicateStackTrace.js:38:2 in symbolicateStackTrace
at http://192.168.3.179:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in __callReactNativeMicrotasks

```

**Comment by Takapy1** [comment]
node_modules一旦削除して、再度npm installしてみる

**Comment by Ayato-kosaka** [comment]
@Takapy1 
yarnlock とpackage lockも消してみるといいかも

**Comment by Takapy1** [comment]
@Ayato-kosaka 
node-modules, lock系全て消してinstallでもだめだ

**Comment by Takapy1** [comment]
@Ayato-kosaka 
MPlacesList.tsxのfirestore読み込みの部分でエラーになってるわ

**Comment by Ayato-kosaka** [comment]
@Takapy1 あとでカフェで起動してみてみるから引き続き何かわかったらここに書いといてー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
iOSで開き方がよくわからなかった、、
今度教えて〜

**Comment by Takapy1** [comment]
Webだとマップ以外は開ける？

**Comment by Takapy1** [comment]
@Ayato-kosaka

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ひらけるよ〜

**Comment by Takapy1** [comment]
なるほどぅ、Xcodeの問題かなー

**Comment by Ayato-kosaka** [comment]
@Takapy1 
↓の手順でやると開けるはず
```
git clone git@github.com:Ayato-kosaka/spelieve.git
git checkout feature/PPA001
npm install -g expo-cli
npm i
expo web
```

**Comment by Takapy1** [comment]
これのせいの可能性が高いな、
なぜかいきなりエラー出るようになっている
<img src="https://user-images.githubusercontent.com/75763679/198816308-030730b9-950f-4fcd-8544-6f6fd556266a.png" size="80x50"

**Comment by Ayato-kosaka** [comment]
@Takapy1 
俺の環境で出てないで！
別のディレクトリ切って git clone からやり直すしかなさそうやね

**Comment by Takapy1** [comment]
@Ayato-kosaka 
今ちょうどこの上のエラーは消えた。

**Comment by Takapy1** [comment]
@Ayato-kosaka
戻せたわ、パッケージマネージャの問題だったっぽいわ。 
node_moduleまた消して、npm installじゃなくてyarn installして
react-native-screens, react-native-safe-area-context追加したらいけた

**Comment by Takapy1** [comment]
@Ayato-kosaka 
closeします

**Comment by Ayato-kosaka** [comment]
@Takapy1 yarn使うでいいの？

**Comment by Ayato-kosaka** [comment]
npm 使う想定だったけど

**Comment by Takapy1** [comment]
@Ayato-kosaka 

package-lick.json復活させて、エラー出ないか明日確かめとくわ

**Comment by Ayato-kosaka** [comment]
おけーい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
明日nonで調べて、成功すればクローズ

**Comment by Takapy1** [comment]
↑npm

**Comment by Takapy1** [comment]
@Ayato-kosaka 
npm

**Comment by Takapy1** [comment]
npm を最新、安定バージョンにしても変わらないな。
基本は俺だけyarnで続けるとかはできないのかな、package.jsonだけ共有していれば、同じだと思ったんだが、

**Comment by Ayato-kosaka** [comment]
@Takapy1 
たしかにそれで開発は出来るからいいんだけど、
npmでエラってるのは解消しとかないと、デプロイする時に重大なミスに気づいてなかったとかやったらまずいから、次の打ち合わせで対面で確認しよ
俺ほぼwebでしかみてないからiOS で問題があるのかもしれんし
