### ISSUE TITLE
Google Map を web 対応する

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#294]
# React native Web, Nativeでライブラリ分ける方法
## １つのファイル内で分岐(webとnativeアプリの場合)
```
import { Platform } from 'react-native';
if (Platform.OS == 'web') {
  // web用ライブラリコンポーネント
} else {
   // native用ライブラリコンポーネント
}
```
- 'web', 'native'や'ios', 'android'なども使える

## ファイルの拡張子で分ける方法（[Platform-specific extensions](https://reactnative.dev/docs/platform-specific-code#platform-specific-extensions)）
```
PMC01101GoogleMapPlacesList
|- GoogleMapPlacesList.native.tsx
|- GoogleMapPlacesList.web.tsx
```
上記のようにファイルを分けることで、Platformによってimport 側で自動的にファイルを分けてくれる
おそらくtypescriptのトランスパイルする対象ファイルの設定をいじる必要はなく、
上記のように拡張子で分けるだけで上手く切り替えてくれる
⚠️index.tsに集めるとエラーが出てきた

## reference
- https://reactnative.dev/docs/platform-specific-code

**Comment by Takapy1** [comment]
Webでのライブラリ
[@react-google-maps/api](https://www.npmjs.com/package/@react-google-maps/api)

Nativeアプリとの切り替え方法
[Platform module](https://reactnative.dev/docs/platform-specific-code)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
対応中にexpo webで開くと以下のエラーが消えない
```
Uncaught TypeError: Object(...) is not a function
    at getDefaultComponent (decorateMapComponent.js:52:1)
    at MapMarker.getAirComponent (decorateMapComponent.js:64:1)
    at MapMarker.render (MapMarker.js:332:1)
    at finishClassComponent (react-dom.development.js:20487:1)
    at updateClassComponent (react-dom.development.js:20433:1)
    at beginWork (react-dom.development.js:22366:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at beginWork$1 (react-dom.development.js:27243:1)
    at performUnitOfWork (react-dom.development.js:26392:1)
    at workLoopSync (react-dom.development.js:26303:1)
    at renderRootSync (react-dom.development.js:26271:1)
    at performSyncWorkOnRoot (react-dom.development.js:25924:1)
    at flushSyncCallbacks (react-dom.development.js:11982:1)
    at flushSyncCallbacksOnlyInLegacyMode (react-dom.development.js:11961:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25326:1)
    at dispatchSetState (react-dom.development.js:17342:1)
    at MPlacesList.tsx:122:1
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
getDefaultComponent @ decorateMapComponent.js:52
getAirComponent @ decorateMapComponent.js:64
render @ MapMarker.js:332
finishClassComponent @ react-dom.development.js:20487
updateClassComponent @ react-dom.development.js:20433
beginWork @ react-dom.development.js:22366
callCallback @ react-dom.development.js:4157
invokeGuardedCallbackDev @ react-dom.development.js:4206
invokeGuardedCallback @ react-dom.development.js:4270
beginWork$1 @ react-dom.development.js:27243
performUnitOfWork @ react-dom.development.js:26392
workLoopSync @ react-dom.development.js:26303
renderRootSync @ react-dom.development.js:26271
performSyncWorkOnRoot @ react-dom.development.js:25924
flushSyncCallbacks @ react-dom.development.js:11982
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11961
scheduleUpdateOnFiber @ react-dom.development.js:25326
dispatchSetState @ react-dom.development.js:17342
(anonymous) @ MPlacesList.tsx:122
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
fetchFirstPlaces @ MPlacesList.tsx:120
(anonymous) @ MPlacesList.tsx:125
commitHookEffectListMount @ react-dom.development.js:22969
commitPassiveMountOnFiber @ react-dom.development.js:24702
commitPassiveMountEffects_complete @ react-dom.development.js:24666
commitPassiveMountEffects_begin @ react-dom.development.js:24653
commitPassiveMountEffects @ react-dom.development.js:24641
flushPassiveEffectsImpl @ react-dom.development.js:26848
flushPassiveEffects @ react-dom.development.js:26801
(anonymous) @ react-dom.development.js:26597
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27329
commitRootImpl @ react-dom.development.js:26596
commitRoot @ react-dom.development.js:26517
performSyncWorkOnRoot @ react-dom.development.js:25956
flushSyncCallbacks @ react-dom.development.js:11982
flushSync @ react-dom.development.js:26040
legacyCreateRootFromDOMContainer @ react-dom.development.js:29309
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29335
render @ react-dom.development.js:29419
render @ index.js:17
renderApplication @ renderApplication.js:23
run @ index.js:38
runApplication @ index.js:81
registerRootComponent @ registerRootComponent.tsx:14
./src/App.tsx @ App.tsx:47
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ PlacePageNavigator.tsx:37
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
10index.js:1 

The above error occurred in the <MapMarker> component:

    at MapMarker (http://192.168.3.179:19006/static/js/bundle.js:109283:81)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at UnimplementedView (http://192.168.3.179:19006/static/js/bundle.js:132336:81)
    at PMC01101GoogleMapPlacesList (http://192.168.3.179:19006/static/js/bundle.js:150884:77)
    at PPA001Places (http://192.168.3.179:19006/static/js/bundle.js:151272:25)
    at StaticContainer (http://192.168.3.179:19006/static/js/bundle.js:34431:16)
    at EnsureSingleNavigator (http://192.168.3.179:19006/static/js/bundle.js:33989:23)
    at SceneView (http://192.168.3.179:19006/static/js/bundle.js:34321:21)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at Background (http://192.168.3.179:19006/static/js/bundle.js:37826:20)
    at Screen (http://192.168.3.179:19006/static/js/bundle.js:38943:107)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at SafeAreaProviderCompat (http://192.168.3.179:19006/static/js/bundle.js:38887:23)
    at NativeStackView (http://192.168.3.179:19006/static/js/bundle.js:39578:20)
    at PreventRemoveProvider (http://192.168.3.179:19006/static/js/bundle.js:34228:24)
    at NavigationContent (http://192.168.3.179:19006/static/js/bundle.js:35726:21)
    at http://192.168.3.179:19006/static/js/bundle.js:35738:26
    at NativeStackNavigator (http://192.168.3.179:19006/static/js/bundle.js:39512:17)
    at PCT011MPlacesListProvider (http://192.168.3.179:19006/static/js/bundle.js:150734:27)
    at PCT012MPlaceOneProvider (http://192.168.3.179:19006/static/js/bundle.js:151097:27)
    at PlacePageNavigator (http://192.168.3.179:19006/static/js/bundle.js:151459:25)
    at StaticContainer (http://192.168.3.179:19006/static/js/bundle.js:34431:16)
    at EnsureSingleNavigator (http://192.168.3.179:19006/static/js/bundle.js:33989:23)
    at SceneView (http://192.168.3.179:19006/static/js/bundle.js:34321:21)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at AnimatedComponent (http://192.168.3.179:19006/static/js/bundle.js:137855:83)
    at AnimatedComponentWrapper
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at BottomNavigationRouteScreen (http://192.168.3.179:19006/static/js/bundle.js:112227:81)
    at AnimatedComponent (http://192.168.3.179:19006/static/js/bundle.js:137855:83)
    at AnimatedComponentWrapper
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at BottomNavigation (http://192.168.3.179:19006/static/js/bundle.js:111672:31)
    at ThemedComponent (http://192.168.3.179:19006/static/js/bundle.js:5981:39)
    at withTheme(BottomNavigation)
    at MaterialBottomTabViewInner (http://192.168.3.179:19006/static/js/bundle.js:39322:21)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at NativeSafeAreaProvider (http://192.168.3.179:19006/static/js/bundle.js:123822:23)
    at SafeAreaProvider (http://192.168.3.179:19006/static/js/bundle.js:123996:23)
    at SafeAreaProviderCompat (http://192.168.3.179:19006/static/js/bundle.js:38887:23)
    at MaterialBottomTabView
    at PreventRemoveProvider (http://192.168.3.179:19006/static/js/bundle.js:34228:24)
    at NavigationContent (http://192.168.3.179:19006/static/js/bundle.js:35726:21)
    at http://192.168.3.179:19006/static/js/bundle.js:35738:26
    at MaterialBottomTabNavigator (http://192.168.3.179:19006/static/js/bundle.js:39210:17)
    at ThemeProvider (http://192.168.3.179:19006/static/js/bundle.js:5862:31)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at PortalHost (http://192.168.3.179:19006/static/js/bundle.js:118085:81)
    at Provider (http://192.168.3.179:19006/static/js/bundle.js:122375:120)
    at EnsureSingleNavigator (http://192.168.3.179:19006/static/js/bundle.js:33989:23)
    at BaseNavigationContainer (http://192.168.3.179:19006/static/js/bundle.js:33656:27)
    at ThemeProvider (http://192.168.3.179:19006/static/js/bundle.js:40372:20)
    at NavigationContainerInner (http://192.168.3.179:19006/static/js/bundle.js:39837:25)
    at App
    at ExpoRootComponent (http://192.168.3.179:19006/static/js/bundle.js:53008:83)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at DevAppContainer (http://192.168.3.179:19006/static/js/bundle.js:52667:81)
    at div
    at http://192.168.3.179:19006/static/js/bundle.js:131076:25
    at AppContainer (http://192.168.3.179:19006/static/js/bundle.js:124501:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
`PMC01101GoogleMapPlacesList`のreturn でPlatformで分岐させれば
```
if(isIOS or isAndroid){
return
		<MapView
			style={{ width: '100%', height: 200 }}
			provider={PROVIDER_GOOGLE}
			ref={(r) => setRef(r)}
			initialRegion={{
				latitude: centerLat,
				longitude: centerLng,
				latitudeDelta: 0.2522, // 地図表示範囲内の北端と南端の緯度の差 大→範囲広
				longitudeDelta: 0.0521, // 地図表示範囲内の東端と西端の経度の差
			}}
			region={{
				latitude: centerLat,
				longitude: centerLng,
				latitudeDelta: 0.2522, // 地図表示範囲内の北端と南端の緯度の差 大→範囲広
				longitudeDelta: 0.0521, // 地図表示範囲内の東端と西端の経度の差
			}}>
			{placesList.map((place) => {
				const coordinate = { latitude: place.geometry.latitude, longitude: place.geometry.longitude };
				return <Marker coordinate={coordinate} title={place.name} key={place.place_id} />;
			})}
		</MapView>
} else {
  // web コンポーネント
}
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なんか分岐させたり、そもそもGoogle mapのコンポーネントを表示させないようにしてもエラーでるんよね

**Comment by Ayato-kosaka** [comment]
@Takapy1 
まじか、参照してないのにエラー出るの謎すぎるな、
野口の環境の問題なのかソースコードの問題なのか、、、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
明日、現段階で適当にブランチ切ってこさの環境で確認してもらおうかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おけー！後で確認する

**Comment by Ayato-kosaka** [comment]
```
git clone git@github.com:Ayato-kosaka/spelieve.git
cd spelieve
git checkout feature/PPA001
npm i -g expo
npm i
expo web
```
してから ENV.ts を追加すると↓が出る
```
Web Bundling complete 1498ms
./node_modules/react-native-maps/src/index.js:23
"export 'Animated' was not found in './MapView'
  21 | 
  22 | export { Marker, Overlay };
> 23 | export { Animated, MAP_TYPES, ProviderPropType, enableLatestRenderer };
  24 | 
  25 | export const PROVIDER_GOOGLE = MapView.PROVIDER_GOOGLE;
  26 | export const PROVIDER_DEFAULT = MapView.PROVIDER_DEFAULT;
./node_modules/react-native-maps/src/index.js:23
"export 'MAP_TYPES' was not found in './MapView'
  21 | 
  22 | export { Marker, Overlay };
> 23 | export { Animated, MAP_TYPES, ProviderPropType, enableLatestRenderer };
  24 | 
  25 | export const PROVIDER_GOOGLE = MapView.PROVIDER_GOOGLE;
  26 | export const PROVIDER_DEFAULT = MapView.PROVIDER_DEFAULT;
./node_modules/react-native-maps/src/index.js:23
"export 'ProviderPropType' was not found in './MapView'
  21 | 
  22 | export { Marker, Overlay };
> 23 | export { Animated, MAP_TYPES, ProviderPropType, enableLatestRenderer };
  24 | 
  25 | export const PROVIDER_GOOGLE = MapView.PROVIDER_GOOGLE;
  26 | export const PROVIDER_DEFAULT = MapView.PROVIDER_DEFAULT;
./node_modules/react-native-maps/src/index.js:23
"export 'enableLatestRenderer' was not found in './MapView'
  21 | 
  22 | export { Marker, Overlay };
> 23 | export { Animated, MAP_TYPES, ProviderPropType, enableLatestRenderer };
  24 | 
  25 | export const PROVIDER_GOOGLE = MapView.PROVIDER_GOOGLE;
  26 | export const PROVIDER_DEFAULT = MapView.PROVIDER_DEFAULT;
./node_modules/react-native-maps/src/decorateMapComponent.js:53:4
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
  51 | 
  52 |   const getDefaultComponent = () =>
> 53 |     requireNativeComponent(getAirComponentName(null, componentType), Component);
     |    ^
  54 | 
  55 |   Component.contextTypes = contextTypes;
  56 | 
./node_modules/react-native-maps/src/decorateMapComponent.js:80:31
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
  78 |         (Platform.OS === 'ios' && googleMapIsInstalled)
  79 |       ) {
> 80 |         components[provider] = requireNativeComponent(componentName, Component);
     |                               ^
  81 |       }
  82 |     } else {
  83 |       // (platformSupport === USES_DEFAULT_IMPLEMENTATION)
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
以下のように2コンポーネント修正したらできたー

**PMC01101GoogleMapPlacesList**
```
import { useContext, useState } from 'react';
import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';

import { PCT011MPlacesList } from '@/Place/Models/PDB01MPlace/Contexts/PCT011MPlacesList';

export const PMC01101GoogleMapPlacesList = () => {
	const { placesList } = useContext(PCT011MPlacesList);
	const [ref, setRef] = useState<MapView | null>(null);

	const center = placesList[0];
	const centerLat = center ? center.geometry.latitude : 35.6809591;
	const centerLng = center ? center.geometry.longitude : 139.7673068;

	return (<></>
		// <MapView
		// 	style={{ width: '100%', height: 200 }}
		// 	provider={PROVIDER_GOOGLE}
		// 	ref={(r) => setRef(r)}
		// 	initialRegion={{
		// 		latitude: centerLat,
		// 		longitude: centerLng,
		// 		latitudeDelta: 0.2522, // 地図表示範囲内の北端と南端の緯度の差 大→範囲広
		// 		longitudeDelta: 0.0521, // 地図表示範囲内の東端と西端の経度の差
		// 	}}
		// 	region={{
		// 		latitude: centerLat,
		// 		longitude: centerLng,
		// 		latitudeDelta: 0.2522, // 地図表示範囲内の北端と南端の緯度の差 大→範囲広
		// 		longitudeDelta: 0.0521, // 地図表示範囲内の東端と西端の経度の差
		// 	}}>
		// 	{placesList.map((place) => {
		// 		const coordinate = { latitude: place.geometry.latitude, longitude: place.geometry.longitude };
		// 		return <Marker coordinate={coordinate} title={place.name} key={place.place_id} />;
		// 	})}
		// </MapView>
	);
};
```


**PMC01201GoogleMapPlaceOne**
```
import { useContext } from 'react';
import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';

import { PCT012MPlaceOne } from '@/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne';

export const PMC01201GoogleMapPlaceOne = () => {
	const { place } = useContext(PCT012MPlaceOne);
	const coordinate = { latitude: place.geometry.latitude, longitude: place.geometry.longitude };

	return (<></>
		// <MapView
		// 	style={{ width: '100%', height: 200 }}
		// 	provider={PROVIDER_GOOGLE}
		// 	initialRegion={{
		// 		latitude: coordinate.latitude,
		// 		longitude: coordinate.longitude,
		// 		latitudeDelta: 0.0062, // 地図表示範囲内の北端と南端の緯度の差 大→範囲広
		// 		longitudeDelta: 0.0062, // 地図表示範囲内の東端と西端の経度の差
		// 	}}>
		// 	<Marker coordinate={coordinate} title={place.name} key={place.place_id} />
		// </MapView>
	);
};
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
俺の環境でも確認してみる

**Comment by Takapy1** [comment]
@Ayato-kosaka 
俺の環境でも消えたわ！

**Comment by Ayato-kosaka** [comment]
@Takapy1 これで、MapViewで検索したら影響調査できたよ！
![image](https://user-images.githubusercontent.com/53715839/200099753-a415b48d-09f2-4a30-b74a-35a82ee2e632.jpeg)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Webとnativeでコンポ切り替えることはできてわ。まだまとまってないからpushしてないけど。

.native、.webみたいな感じでファイルを分けれるらしいんだけどtypescript の問題起こりそうだから一旦一つのファイルの中で条件分岐する流れにします。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
了解した！

https://github.com/Ayato-kosaka/spelieve/issues/294

まとまったら、ここに書いて、document タグを付けてくれるととても助かります！

**Comment by Takapy1** [comment]
# React native Web, Nativeでライブラリ分ける方法
## １つのファイル内で分岐
```
import { Platform } from 'react-native';
if (Platform.OS == 'web') {
  // web用ライブラリコンポーネント
} else {

}

```

**Comment by Takapy1** [comment]
@Ayato-kosaka
Web対応できたから、feature/PPA001をpullして、PlacePageNavigatorのLoadScriptのコメントアウトを戻せば、
動作は見れる状態

問題点
Google Map表示のためには下のような構造である必要があって、
LoadSciptでAPIキーを設定するんだけど、このタグが一回しか使えない制限があって、
Stackの中にかけない！
今はPlacePageNavigatorに記述している。
→コメントアウト外すと、WebではみれるがIOSで動かなくなる
　→PlacePageNavigatorをWeb、Nativeで分けなくてはいけなくなる！
```
<LoadScript　googleMapsApiKey={ENV.GCP_API_KEY}>>
  <GoogleMap />
</LoadScript>
```
NativeアプリとWebの方でスタイル、ライブラリとかの相違がかなり大きくなってきそうだから、
ディレクトリ構成も含め話し合いたい

**Comment by Ayato-kosaka** [comment]
@Takapy1 
`PlacePageNavigator`に`LoadScript`を書くとiOSでエラーになるってことね。
明日の諸々相談会で話し会おう！
パット見、
```
PlacePageNavigator
|- index.ts
|- PlacePageNavigator.tsx
|- PlacePageNavigator.provider.native.tsx
|- PlacePageNavigator.provider.web.tsx
```

みたいにすれば解決思想かなって思ってるけど
