### ISSUE TITLE
IOS でPPA001 が開けない

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#316]

**Comment by Takapy1** [comment]
```
[2022-11-14T10:50:40.926Z]  @firebase/firestore:, Firestore (9.14.0): INTERNAL UNHANDLED ERROR: , t is not an Object. (evaluating '"nullValue" in t')

me@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:147620:27
we@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:147617:14
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:148061:70
map@[native code]
ke@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:148060:111
dn@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:148539:14
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:158253:16
get@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:149174:30
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:158264:26
generatorResume@[native code]
asyncGeneratorStep@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:22067:26
_next@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:22086:29
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:22091:14
tryCallTwo@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:26832:9
doResolve@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:26964:25
Promise@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:26851:14
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:22083:25
_Qu@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:158276:21
Qu@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:158257:21
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:160905:18
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:160906:8
generatorResume@[native code]
asyncGeneratorStep@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:22067:26
_next@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:22086:29
tryCallOne@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:26824:16
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:26905:27
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:27849:26
_callTimer@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:27764:17
_callReactNativeMicrotasksPass@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:27797:17
callReactNativeMicrotasks@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:27961:44
__callReactNativeMicrotasks@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:21186:46
@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:20986:45
__guard@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:21166:15
flushedQueue@http://192.168.3.21:19000/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:20985:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
at node_modules/@firebase/logger/dist/index.cjs.js:89:29 in defaultLogHandler
at node_modules/@firebase/logger/dist/index.cjs.js:203:30 in Logger.prototype.error
at node_modules/@firebase/firestore/dist/index.rn.js:124:15 in N
at node_modules/@firebase/firestore/dist/index.rn.js:17063:19 in <anonymous>

[Unhandled promise rejection: TypeError: t is not an Object. (evaluating '"nullValue" in t')]

at node_modules/@firebase/firestore/dist/index.rn.js:3202:26 in me
at node_modules/@firebase/firestore/dist/index.rn.js:3198:13 in we
at node_modules/@firebase/firestore/dist/index.rn.js:3631:73 in e.filters.map$argument_0
at node_modules/@firebase/firestore/dist/index.rn.js:3630:103 in ke
at node_modules/@firebase/firestore/dist/index.rn.js:4115:16 in an
at node_modules/@firebase/firestore/dist/index.rn.js:14113:38 in $u#constructor
at node_modules/@firebase/firestore/dist/index.rn.js:4984:31 in <global>
at node_modules/@firebase/firestore/dist/index.rn.js:14120:33 in $u
at node_modules/@firebase/firestore/dist/index.rn.js:14132:1 in $u
at node_modules/@firebase/firestore/dist/index.rn.js:14118:17 in $u#constructor
at node_modules/@firebase/firestore/dist/index.rn.js:16861:17 in wa#Mc
at node_modules/@firebase/firestore/dist/index.rn.js:16862:5 in wa#Mc
```
