### ISSUE TITLE
PMC01202PlaceInformationのFlatList をmapに変更する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#377]
## Why
下記エラーがiosで出るため
```
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
at node_modules/react-native/Libraries/Lists/VirtualizedList.js:1146:27 in ScrollView.Context.Consumer.props.children
at src/Place/Models/PDB01MPlace/Contexts/PCT012MPlaceOne/MPlaceOne.tsx:102:15 in fetchData
```

## What
PMC01202PlaceInformationのFlatList をmapに変更する

## 子issue
- [ ]

**Comment by Ayato-kosaka** [comment]
とりあえず起票

**Comment by Ayato-kosaka** [comment]
https://github.com/Ayato-kosaka/spelieve/commit/313a0336eee0fb30b62c46a346815a2adb5112b9
これを参考にしてほしい！
@Takapy1
