### ISSUE TITLE
ネイティブ版の Admob を導入する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#563]
# 導入
## ゴール
[react-native-google-mobile-ads](https://github.com/invertase/react-native-google-mobile-ads)を導入する
⚠️react-native-google-mobile-adsはManaged workflowでは使用できないライブラリである。
→expo start --iosとかで実行しても動かない
そのため、動作確認をしたい時はGithub Action回して、expo start --dev-clientでBara workflowにする必要あり

## 手順
- [x] [admobコンソール] Admob登録
- [x] [メンバー追加](https://support.google.com/admob/answer/10838527?hl=ja)
- [x] アプリの追加([詳細](https://support.google.com/admob/answer/9989980?hl=ja#zippy=%2Cgoogle-play-%E3%82%B9%E3%83%88%E3%82%A2%E3%81%BE%E3%81%9F%E3%81%AF-apple-app-store-%E3%81%AB%E6%8E%B2%E8%BC%89%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%82%A2%E3%83%97%E3%83%AA))
  - [x] ⚠️[はい、アプリはサポートされているアプリストアに登録されています] を選択
  - [x] 審査
- [x] [アプリ内] インストール、初期設定
- [ ] [admobコンソール]プライバシー設定 (必須ではない)
- [x] テスト表示
- [ ] 本番環境に設置

### モジュールインストール
⚠️[Androidの場合] アプリの設定で「my app contains ads in the Google Play Store, Policy, App content, Manage under Ads」にする。（TODO: 設定場所はどこだ）
```
# Install the admob module
yarn add react-native-google-mobile-ads
```

### [app.json設定](https://docs.expo.dev/versions/latest/sdk/build-properties/)
Android, iOSのアプリIDを設定する
Expoユーザなら下記の記述
→
⚠️ドキュメントではそうだが、app.config.tsで以下の記述はできないため、
[expo app.config.tsのプロパティ一覧](https://docs.expo.dev/versions/latest/config/app/#googlemobileadsappid)からadmobのプロパティ見て解決
```
// <project-root>/app.json
{
  "expo": {
    // ...
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx"
  }
}

## 広告表示方法
- [バナー広告参考予定ドキュメント](https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads#banner-ads-component)
- 広告の種類4種類くらいある、各種類がどんな広告かは[ドキュメント参照](https://developers.google.com/admob/android/app-open?hl=ja)

```
### app.jsonの変更を反映
⚠️Expo(EAS)なので以下のコマンド
```
npx eas-cli build --profile development
```

# 参考
[手順参考](https://zenn.dev/hal1986/books/react-native-monetize/viewer/1_admob)
[公式ドキュメント](https://docs.page/invertase/react-native-google-mobile-ads)

**Comment by Ayato-kosaka** [comment]
https://docs.expo.dev/versions/v45.0.0/sdk/admob/
これで出来そう

**Comment by Takapy1** [comment]
Google adsenceと統合できるか確認

**Comment by Takapy1** [comment]
@Ayato-kosaka 
admobアカウントをGoogleアカウントから作成する必要があるんだけど、
アカウントどうしようか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
手順分かれば作っておくよー

**Comment by Takapy1** [comment]
@Ayato-kosaka 
https://support.google.com/admob/answer/7356219?hl=ja#:~:text=https%3A%2F%2Fapps.admob.com,%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E3%82%92%E4%BD%9C%E6%88%90%E3%81%97%E3%81%BE%E3%81%99%E3%80%82
の手順でお願いしてもいいですか

**Comment by Ayato-kosaka** [comment]
携帯でできなかったから、帰ってパソコンでやるわ！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
遅くなって申し訳ない！
AdMob登録＆招待完了した！
審査も始まったみたい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
開発環境でアプリをビルドし直す方法覚えてたら教えて欲しい！
developmentのENVで
```
$ eas build --profile development
```
しても失敗している状況です。
https://expo.dev/accounts/spelieve/projects/Spelieve/builds/d387d01a-ce1c-4f63-bb7a-dbfc3b84045f

**Comment by Ayato-kosaka** [comment]
@Takapy1 
eas-build-develop じゃなかったっけ、

https://github.com/Ayato-kosaka/spelieve/actions/workflows/eas-build-develop.yml

**Comment by Takapy1** [comment]
開発環境のビルドしたものをシミュレータで動作確認する時って

1. 自分のブランチでdevelopのgithub Actionの流してビルド
2. ビルド完了したものをeasコマンドでシミュレータ表示

この流れだっけ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
1はあってる！
ビルドした後、モバイルにダウンロードして、
ローカルブランチで、　expo start --dev-client でできる！

**Comment by Takapy1** [comment]
install modules
babel-plugin-react-native-web webpack webpack-cli webpack-dev-server

**Comment by Takapy1** [comment]
```
Linking requires a build-time setting `scheme` in the project's Expo config (app.config.js or app.json) for bare or production apps. Manually providing a `scheme` property can circumvent this warning. Using native app identifier as the scheme 'com.spelieve'. Learn more: https://docs.expo.dev/guides/linking/
at node_modules/expo-linking/build/Schemes.js:143:20 in resolveScheme
at node_modules/expo-linking/build/Linking.js:128:40 in createURL
at src/Common/Navigation/LinkingConfiguration.ts:73:21 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:373:11 in loadModuleImplementation
at src/Common/Navigation/Navigation.tsx:10:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:373:11 in loadModuleImplementation
at src/App.tsx:8:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:373:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:234:44 in guardedLoadModule
at http://192.168.3.179:8081/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
developブランチからexpo webを起動しても
以下のエラーが出るんだけど俺の環境の問題なのかな
```
WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/Header.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/Header.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/Header.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackButton.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderBackButton.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderBackButton.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackContext.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderBackContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderBackContext.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackground.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderBackground.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderBackground.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderHeightContext.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderHeightContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderHeightContext.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderShownContext.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderShownContext.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderShownContext.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/HeaderTitle.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderTitle.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/HeaderTitle.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/getDefaultHeaderHeight.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/getDefaultHeaderHeight.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/getDefaultHeaderHeight.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/getHeaderTitle.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/getHeaderTitle.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/getHeaderTitle.tsx'

WARNING in ./node_modules/@react-navigation/elements/lib/module/Header/useHeaderHeight.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/useHeaderHeight.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/elements/lib/src/useHeaderHeight.tsx'

WARNING in ./node_modules/@react-navigation/material-bottom-tabs/lib/module/navigators/createMaterialBottomTabNavigator.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-bottom-tabs/lib/src/createMaterialBottomTabNavigator.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-bottom-tabs/lib/src/createMaterialBottomTabNavigator.tsx'

WARNING in ./node_modules/@react-navigation/material-bottom-tabs/lib/module/views/MaterialBottomTabView.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-bottom-tabs/lib/src/MaterialBottomTabView.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-bottom-tabs/lib/src/MaterialBottomTabView.tsx'

WARNING in ./node_modules/@react-navigation/material-top-tabs/lib/module/navigators/createMaterialTopTabNavigator.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-top-tabs/lib/src/createMaterialTopTabNavigator.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-top-tabs/lib/src/createMaterialTopTabNavigator.tsx'

WARNING in ./node_modules/@react-navigation/material-top-tabs/lib/module/views/MaterialTopTabBar.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-top-tabs/lib/src/MaterialTopTabBar.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-top-tabs/lib/src/MaterialTopTabBar.tsx'

WARNING in ./node_modules/@react-navigation/material-top-tabs/lib/module/views/MaterialTopTabView.js
Module Warning (from ../../../../.nodebrew/node/v16.13.2/lib/node_modules/expo-cli/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-top-tabs/lib/src/MaterialTopTabView.tsx' file: Error: ENOENT: no such file or directory, open '/Users/ganeshatakahiro/Documents/Spelive/experiment/spelieve/node_modules/@react-navigation/material-top-tabs/lib/src/MaterialTopTabView.tsx'

```

**Comment by Ayato-kosaka** [comment]
うわ、ほんとだエラってる、、
すぐ直します！
ローカルでは何故か出てなかったから気づかなかった
![image](https://user-images.githubusercontent.com/53715839/217550041-892f0e33-53a0-468c-8bff-5b4c7dd2003e.png)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
俺のローカルの expo-cli が 6.0.1 だったから出なかったんだ
直せそうだったら直しておくからそれまで無視でも大丈夫？
warning だから画面は開くよね

**Comment by Takapy1** [comment]
@Ayato-kosaka おけーい

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おそらく上記のwarningにより,Hello Spelieveが無限レンダリングしていそう
Hello Spelieve内にconsole設置したときのブラウザ挙動
↓
<img width="902" alt="スクリーンショット 2023-02-09 8 15 31" src="https://user-images.githubusercontent.com/75763679/217673340-c931635f-7ffb-477e-a550-5e6a5b521de3.png">

**Comment by Ayato-kosaka** [comment]
@Takapy1 
どうやら無限ループしてるのって本番環境でもそうみたい。
HelloSpelieveのuseEffectコメントアウトすれば一旦回避できる！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
これは謎だな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
今 iSO の admob が HelloSpelive のトップに出てるんだけど、ここに出すっていう整理だったっけ？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
どこに出すのか決まってなくて、helloにだけある状態だと思う。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
いや、まって会議の時に決めた気がする！
でも修正せずにそのままなだけだ。
決めた時にどこにメモってのか覚えてないけど

**Comment by Takapy1** [comment]
@Ayato-kosaka 

発見した
https://github.com/Ayato-kosaka/spelieve/discussions/583
の2023/01/24 Spelieve 検討会にあったわ

**Comment by Takapy1** [comment]
@Ayato-kosaka
もしマージ前だったら、該当箇所に広告の設置できそう？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとー！
配置しておくわ！
