### ISSUE TITLE
select template でエラーが出る

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#815]
## Description
web の select template でエラーが出る

![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/f2a9ea4d-9b1e-426c-81e5-281fd7e22679)

![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/40d0e92d-1212-410f-ae3a-342662265d3c)

```
debug IDB01/Itineraries read docSnap.id BTgxXSVzlZRnlhbjj1UD
8GestureDetector.tsx:150 Uncaught ReferenceError: setImmediate is not defined
    at attachHandlers (GestureDetector.tsx:150:1)
    at GestureDetector.tsx:651:1
    at commitHookEffectListMount (react-dom.development.js:23049:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:1)
    at commitPassiveMountEffects (react-dom.development.js:24756:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:1)
    at flushPassiveEffects (react-dom.development.js:26935:1)
    at performSyncWorkOnRoot (react-dom.development.js:26032:1)
attachHandlers @ GestureDetector.tsx:150
(anonymous) @ GestureDetector.tsx:651
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
performSyncWorkOnRoot @ react-dom.development.js:26032
flushSyncCallbacks @ react-dom.development.js:12009
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11988
scheduleUpdateOnFiber @ react-dom.development.js:25438
enqueueSetState @ react-dom.development.js:13264
Component.setState @ react.development.js:352
(anonymous) @ PortalManager.tsx:20
(anonymous) @ PortalHost.tsx:78
(anonymous) @ PortalConsumer.tsx:16
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
componentDidMount @ PortalConsumer.tsx:17
commitLayoutEffectOnFiber @ react-dom.development.js:23204
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11988
scheduleUpdateOnFiber @ react-dom.development.js:25438
dispatchSetState @ react-dom.development.js:17389
(anonymous) @ DecorationsMap.tsx:60
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
fetchData @ DecorationsMap.tsx:51
(anonymous) @ DecorationsMap.tsx:64
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
performSyncWorkOnRoot @ react-dom.development.js:26032
flushSyncCallbacks @ react-dom.development.js:12009
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11988
scheduleUpdateOnFiber @ react-dom.development.js:25438
dispatchSetState @ react-dom.development.js:17389
(anonymous) @ ThumbnailOne.tsx:59
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
fetchData @ ThumbnailOne.tsx:52
(anonymous) @ ThumbnailOne.tsx:63
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
(anonymous) @ react-dom.development.js:26725
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
8react_devtools_backend_compact.js:2367 The above error occurred in the <GestureDetector> component:

    at GestureDetector (http://localhost:19006/static/js/bundle.js:30616:29)
    at TCO001GestureProvider (http://localhost:19006/static/js/bundle.js:93667:22)
    at TMC02301Decoration (http://localhost:19006/static/js/bundle.js:94403:27)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at ViewShot (http://localhost:19006/static/js/bundle.js:69298:86)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at http://localhost:19006/static/js/bundle.js:71059:21
    at TPA001ThumbnailEditor (http://localhost:19006/static/js/bundle.js:96586:25)
    at StaticContainer (http://localhost:19006/static/js/bundle.js:14155:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:13711:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:14045:21)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at Background (http://localhost:19006/static/js/bundle.js:17414:20)
    at Screen (http://localhost:19006/static/js/bundle.js:18390:100)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:18334:23)
    at NativeStackView (http://localhost:19006/static/js/bundle.js:19288:20)
    at PreventRemoveProvider (http://localhost:19006/static/js/bundle.js:13955:24)
    at NavigationContent (http://localhost:19006/static/js/bundle.js:15368:21)
    at http://localhost:19006/static/js/bundle.js:15379:26
    at NativeStackNavigator (http://localhost:19006/static/js/bundle.js:19219:17)
    at TCT032MMaskShapeListProvider (http://localhost:19006/static/js/bundle.js:94672:23)
    at TCT023DecorationsMapProvider (http://localhost:19006/static/js/bundle.js:94281:23)
    at TCT011MThumbnailOneProvider (http://localhost:19006/static/js/bundle.js:94097:23)
    at TCT012MThumbnailListProvider (http://localhost:19006/static/js/bundle.js:94196:23)
    at ThumbnailPageNavigator
    at StaticContainer (http://localhost:19006/static/js/bundle.js:14155:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:13711:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:14045:21)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at Background (http://localhost:19006/static/js/bundle.js:17414:20)
    at Screen (http://localhost:19006/static/js/bundle.js:18390:100)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:18334:23)
    at NativeStackView (http://localhost:19006/static/js/bundle.js:19288:20)
    at PreventRemoveProvider (http://localhost:19006/static/js/bundle.js:13955:24)
    at NavigationContent (http://localhost:19006/static/js/bundle.js:15368:21)
    at http://localhost:19006/static/js/bundle.js:15379:26
    at NativeStackNavigator (http://localhost:19006/static/js/bundle.js:19219:17)
    at CCO001ThumbnailEditorProvider (http://localhost:19006/static/js/bundle.js:87173:23)
    at CCO001GlobalContext (http://localhost:19006/static/js/bundle.js:87194:24)
    at RootNavigator
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:13711:23)
    at BaseNavigationContainer (http://localhost:19006/static/js/bundle.js:13378:27)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:19878:20)
    at NavigationContainerInner (http://localhost:19006/static/js/bundle.js:19545:25)
    at Navigation (http://localhost:19006/static/js/bundle.js:88142:107)
    at LoadScript (http://localhost:19006/static/js/bundle.js:2118:86)
    at AppProvider (http://localhost:19006/static/js/bundle.js:87143:23)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:104474:31)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at PortalHost (http://localhost:19006/static/js/bundle.js:42821:86)
    at Provider (http://localhost:19006/static/js/bundle.js:45789:125)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at NativeSafeAreaProvider (http://localhost:19006/static/js/bundle.js:66648:23)
    at SafeAreaProvider (http://localhost:19006/static/js/bundle.js:66806:23)
    at App
    at withDevTools(App)
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at div
    at http://localhost:19006/static/js/bundle.js:74118:25
    at AppContainer (http://localhost:19006/static/js/bundle.js:69658:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend_compact.js:2367
logCapturedError @ react-dom.development.js:18572
update.callback @ react-dom.development.js:18605
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23290
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11988
scheduleUpdateOnFiber @ react-dom.development.js:25438
enqueueSetState @ react-dom.development.js:13264
Component.setState @ react.development.js:352
(anonymous) @ PortalManager.tsx:20
(anonymous) @ PortalHost.tsx:78
(anonymous) @ PortalConsumer.tsx:16
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
componentDidMount @ PortalConsumer.tsx:17
commitLayoutEffectOnFiber @ react-dom.development.js:23204
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11988
scheduleUpdateOnFiber @ react-dom.development.js:25438
dispatchSetState @ react-dom.development.js:17389
(anonymous) @ DecorationsMap.tsx:60
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
fetchData @ DecorationsMap.tsx:51
(anonymous) @ DecorationsMap.tsx:64
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
performSyncWorkOnRoot @ react-dom.development.js:26032
flushSyncCallbacks @ react-dom.development.js:12009
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:11988
scheduleUpdateOnFiber @ react-dom.development.js:25438
dispatchSetState @ react-dom.development.js:17389
(anonymous) @ ThumbnailOne.tsx:59
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
fetchData @ ThumbnailOne.tsx:52
(anonymous) @ ThumbnailOne.tsx:63
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
(anonymous) @ react-dom.development.js:26725
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
:19006/ThumbnailEditor?fromThumbnailID=sakura-1_1:1 Access to image at 'https://storage.googleapis.com/itinerary-4aee3.appspot.com/MMaskShape/circle.png?GoogleAccessId=firebase-adminsdk-xpn9p%40itinerary-4aee3.iam.gserviceaccount.com&Expires=16730323200&Signature=jE5LftyElGHxi1zalhS9kQbATxdsPB4et1616iwvrg3Hkpy8UiX09rRZOn4LE11hF7Fcl%2BO8FZ%2BRvgUIgAZ0bYyB3LjjmMN8HD4Tg9xtVLwLymg70NOh6P7%2F2jC84wsRTcwQZdkY6X9%2FvQLYpvTyOGjLevobkOwx0hfjrFZDvnCSF9WV7DTzWtRbcewc%2F1GLd4GTVtP978cuB1c9mYgQa53XBvd8svlRbwYx0CC6e5DjuWTUlIt5sSo5Q2yEUssWB2yVsnkxcA0VdAr4dRK81dmePHEzs8ONzZkS4HK2WWVK6MpeMxO1u%2FpJk66IvKEF5BfmviJwdwy6w%2BXEWRD11w%3D%3D' from origin 'http://localhost:19006' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
storage.googleapis.com/itinerary-4aee3.appspot.com/MMaskShape/circle.png?GoogleAccessId=firebase-adminsdk-xpn9p%40itinerary-4aee3.iam.gserviceaccount.com&Expires=16730323200&Signature=jE5LftyElGHxi1zalhS9kQbATxdsPB4et1616iwvrg3Hkpy8UiX09rRZOn4LE11hF7Fcl%2BO8FZ%2BRvgUIgAZ0bYyB3LjjmMN8HD4Tg9xtVLwLymg70NOh6P7%2F2jC84wsRTcwQZdkY6X9%2FvQLYpvTyOGjLevobkOwx0hfjrFZDvnCSF9WV7DTzWtRbcewc%2F1GLd4GTVtP978cuB1c9mYgQa53XBvd8svlRbwYx0CC6e5DjuWTUlIt5sSo5Q2yEUssWB2yVsnkxcA0VdAr4dRK81dmePHEzs8ONzZkS4HK2WWVK6MpeMxO1u%2FpJk66IvKEF5BfmviJwdwy6w%2BXEWRD11w%3D%3D:1          GET https://storage.googleapis.com/itinerary-4aee3.appspot.com/MMaskShape/circle.png?GoogleAccessId=firebase-adminsdk-xpn9p%40itinerary-4aee3.iam.gserviceaccount.com&Expires=16730323200&Signature=jE5LftyElGHxi1zalhS9kQbATxdsPB4et1616iwvrg3Hkpy8UiX09rRZOn4LE11hF7Fcl%2BO8FZ%2BRvgUIgAZ0bYyB3LjjmMN8HD4Tg9xtVLwLymg70NOh6P7%2F2jC84wsRTcwQZdkY6X9%2FvQLYpvTyOGjLevobkOwx0hfjrFZDvnCSF9WV7DTzWtRbcewc%2F1GLd4GTVtP978cuB1c9mYgQa53XBvd8svlRbwYx0CC6e5DjuWTUlIt5sSo5Q2yEUssWB2yVsnkxcA0VdAr4dRK81dmePHEzs8ONzZkS4HK2WWVK6MpeMxO1u%2FpJk66IvKEF5BfmviJwdwy6w%2BXEWRD11w%3D%3D net::ERR_FAILED 200
GestureDetector.tsx:150 Uncaught (in promise) ReferenceError: setImmediate is not defined
    at attachHandlers (GestureDetector.tsx:150:1)
    at GestureDetector.tsx:651:1
    at commitHookEffectListMount (react-dom.development.js:23049:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:1)
    at commitPassiveMountEffects (react-dom.development.js:24756:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:1)
    at flushPassiveEffects (react-dom.development.js:26935:1)
    at performSyncWorkOnRoot (react-dom.development.js:26032:1)
```

**Comment by Ayato-kosaka** [comment]
Access to image at 'https://storage.googleapis.com/itinerary-4aee3.appspot.com/MMaskShape/circle.png?GoogleAccessId=firebase-adminsdk-xpn9p%40itinerary-4aee3.iam.gserviceaccount.com&Expires=16730323200&Signature=jE5LftyElGHxi1zalhS9kQbATxdsPB4et1616iwvrg3Hkpy8UiX09rRZOn4LE11hF7Fcl%2BO8FZ%2BRvgUIgAZ0bYyB3LjjmMN8HD4Tg9xtVLwLymg70NOh6P7%2F2jC84wsRTcwQZdkY6X9%2FvQLYpvTyOGjLevobkOwx0hfjrFZDvnCSF9WV7DTzWtRbcewc%2F1GLd4GTVtP978cuB1c9mYgQa53XBvd8svlRbwYx0CC6e5DjuWTUlIt5sSo5Q2yEUssWB2yVsnkxcA0VdAr4dRK81dmePHEzs8ONzZkS4HK2WWVK6MpeMxO1u%2FpJk66IvKEF5BfmviJwdwy6w%2BXEWRD11w%3D%3D' from origin 'http://localhost:19006/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
→ このエラーメッセージは、画像の読み込み時にCORS（Cross-Origin Resource Sharing）のポリシーに違反しているため、アクセスがブロックされたことを示しています。ブラウザーはセキュリティ上の理由から、異なるオリジン（ドメイン、ポート、プロトコル）からのリソースへのアクセスを制限しています。

**Comment by Ayato-kosaka** [comment]
https://github.com/necolas/react-native-web/issues/1891#issuecomment-887502705
で、解決
