### ISSUE TITLE
PlanGroupを跨いで、移動させるとUncaught Errorになる

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#825]
### 1こ目のPlanGroupの最下をdownして、2こ目の先頭に移動するか検証
SwapPlan関数内でエラー起きてそう
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at PlanGroupsList.tsx:96:1
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:1
    at PlanGroupsList.tsx:110:1
    at PlanEditController.ts:270:1
    at Generator.next (<anonymous>)
```
movePlanUpAndDownの以下の第一引数selectedIndexが{planGroup: -1, plan: 1}になっている
```
await swapPlanOrder(selectedIndex, {
						planGroup: planGroupIndex + 1,
						plan: 0,
					});
```

 ### なぜ-1になっているか？
追加した以下コードですでに-1が代入されている
```
const planGroupIndex: number | undefined = planGroupsQSnap?.docs.indexOf(planGroupsDoc);
console.log("planGroupIndex: ", planGroupIndex)  // ここで-1になってる
```

### [JSのindexOfメソッド](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)
存在しないと-1返すらしい
```
The indexOf() method returns the first index at which a given element can be found in the array, or -1 if it is not present.
```

**Comment by Ayato-kosaka** [comment]
const planGroupIndex = planGroupsQSnap?.docs.map(d=>d.id).indexOf(planGroupsDoc.id);
