### ISSUE TITLE
Androidアプリの方がバージョンが古くて更新できない

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#870]
## 修正ブランチ
#871 

## Description
以下の画像にあるように、Androidアプリが古いバージョンの APIを対象としているのでリリースできない
<img width="1402" alt="スクリーンショット 2023-10-10 20 12 40" src="https://github.com/Ayato-kosaka/spelieve/assets/75763679/405c6d21-417d-4b1b-9a48-58e6af134b36">

Play Console 問題詳細画面
https://play.google.com/console/u/0/developers/8574450267489544535/app/4973542470181743218/policy-center/issues/4988462738182909742/details

## 調査
現状の対象APIレベルは「31」
満たすべき対象APIレベルは「33」
よって、31→33にするための対処をする。
そのための説明は以下のリンクに書いてある。
https://developer.android.com/google/play/requirements/target-sdk?hl=ja#pre13

## 解決案
Expo SDKをアップデートするだけでOK
Expo SDKを最新に保っていればこちらで特に記述しなくてもAPIレベルの制限に引っかからない
### Expo SDKをアップデート
これを実行すると、プロジェクト内Expo関連のpackageを全てアップデートしてくれる
今回、**Expo SDKのバージョンが47→49**に変更した。
```bash
$ expo upgrade
```

## 確認
以下のように、Expo SDKのバージョンを47→49にしたので、AndroidのcompileSdkVersionも33になる。
（Expo SDKがversion47だったからAPIレベルは31だったのか！）

<img width="1077" alt="スクリーンショット 2023-10-14 14 05 05" src="https://github.com/Ayato-kosaka/spelieve/assets/75763679/4832b9d7-be5f-4c13-a04d-943995c38c82">

[【Expo公式】Expo SDK versionとAnroidのcompileSdkVersionの対応表](https://docs.expo.dev/versions/latest/#support-for-android-and-ios-versions)

## その他
期限の延長も可能！（その場合11/1までに対応してリリースしなくてはいけない！)

## その他試したこと
対象APIレベル確認→どこに書いてあるか不明だった
```
$  npx expo-env-info
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nodebrew/current/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nodebrew/current/bin/npm
      Watchman: 2023.10.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/ganeshatakahiro/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 3.1.0
      expo-cli: 6.3.10
    Expo Workflow: managed

```

**Comment by Ayato-kosaka** [comment]
なんなんだろこれ、、、

**Comment by Takapy1** [comment]
以下のようにapp.config.tsないを修正すればいけそうだけど、
修正してマージすると
premain, developのバージョンがiOSとずれちゃうよね？

```javascript
"expo": {
  "android": {
    "targetSdkVersion": 33
  }
}
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おぉー
iOSのリリース消せばいいんじゃね笑

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確かに！そうしよう！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
一番上の調査結果更新しました。
おそらくこの解決方法で治ると思う。

packageアップデートしたので、この後アプリが問題なく動くか確認でき次第
マージリクエスト作成します。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！
Expo upgrade しないといけないってことだよね！
モンキーテストしないと怖いからPR作ってくれたら、俺も叩いてみるわ〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
マージリクエスト作成した！
こさの方でもモンキーテストお願いします
https://github.com/Ayato-kosaka/spelieve/pull/874

**Comment by Ayato-kosaka** [comment]
おけーい

**Comment by Takapy1** [comment]
@Ayato-kosaka 
前にapp.configに追加したやつ消してpushするからちょいテストお待ち

**Comment by Takapy1** [comment]
@Ayato-kosaka 
expo --dev-clientでアプリ開くと以下のエラーになる
```bash
iOS Bundling failed 4197ms
While trying to resolve module `make-plural` from file `/Users/ganeshatakahiro/Documents/Spelieve/spelieve/node_modules/i18n-js/dist/import/Pluralization.js`, 
the package `/Users/ganeshatakahiro/Documents/Spelieve/spelieve/node_modules/make-plural/package.json` was successfully found. 
However, this package itself specifies a `main` module field that could not be resolved (`/Users/ganeshatakahiro/Documents/Spelieve/spelieve/node_modules/make-plural/plurals.mjs`. Indeed, none of these files exist:

  * /Users/ganeshatakahiro/Documents/Spelieve/spelieve/node_modules/make-plural/plurals.mjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  * /Users/ganeshatakahiro/Documents/Spelieve/spelieve/node_modules/make-plural/plurals.mjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
```
## 試したけど未解決
node-modulesとpackage-lock.json消して`npm install`しても意味なし

**Comment by Ayato-kosaka** [comment]
@Takapy1 
俺も試した見たけど、↓のエラーが出るなぁ、、、
```
Logs for your project will appear below. Press Ctrl+C to exit.
Started Metro Bundler
Error: Problem validating fields in app.json. Learn more.
 • Field: android - should NOT have additional property 'targetSdkVersion'.
Error: Problem validating fields in app.json. Learn more.
 • Field: android - should NOT have additional property 'targetSdkVersion'.
iOS Bundling complete 6779ms

TypeError: _ReanimatedModule.default.createNode is not a function (it is undefined), js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:46:19 in errorHandler
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:51:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:237:40 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:131:23 in metroRequire
at http://9k-gtc.anonymous.spelieve.exp.direct:80/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
- ... 7 more stack frames from framework internals

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
- ... 7 more stack frames from framework internals
```

**Comment by Ayato-kosaka** [comment]
https://github.com/Ayato-kosaka/spelieve/actions/runs/6516146773/job/17699342653
Preview のJOBも落ちてるねぇ、、

**Comment by Ayato-kosaka** [comment]
```
Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
- ... 7 more stack frames from framework internals

TypeError: _ReanimatedModule.default.createNode is not a function (it is undefined), js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:46:19 in errorHandler
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:51:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:237:40 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:131:23 in metroRequire
at http://9k-gtc.anonymous.spelieve.exp.direct:80/src/App.tsx.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
- ... 7 more stack frames from framework internals
```

**Comment by Ayato-kosaka** [comment]
/remind me to Release Android at 09:00 November 1

**Comment by Ayato-kosaka** [comment]
/remind me to Release Android 09:00 November 1

**Comment by Ayato-kosaka** [comment]
/remind me to Release Android November 1

**Comment by Ayato-kosaka** [comment]
/remind me to Release Android November 1 9 am

**Comment by Ayato-kosaka** [comment]
↑のリマンインだークソだ
時間ある時に見ないと

**Comment by Ayato-kosaka** [comment]
preMain にマージしてみた結果

https://expo.dev/accounts/spelieve/projects/Spelieve/submissions/7410fd55-166e-4854-850f-e2dd8401b8f5
そもそも Submition で失敗している

@Takapy1 
前回 preMain にマージした時（このチケット切った時）って、 Submition 自体は成功してたけど、Google play store で怒られたって認識で合ってる？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Submit は成功してたよ。
ただビルドしたものが古かったから怒られてただけだったと思う

**Comment by Ayato-kosaka** [comment]
あ、やべ、、
Version code 11 has already been used だ、
手順書読まずにやっちゃった。ごめんなさい > @Takapy1

**Comment by Takapy1** [comment]
@Ayato-kosaka 
うぃーー！
てかみないでやってよくミス1つでおさまったな笑笑すごいわ

**Comment by Ayato-kosaka** [comment]
Expo upgrade で変更された依存関係は大体解消したけど、
一件↓の事象が発生して解決しないなぁ〜
30分前に投稿されてるから、今発生しているのかも！

https://github.com/invertase/react-native-firebase/issues/386#issuecomment-1826539621

**Comment by Ayato-kosaka** [comment]
`npx expo start --web`を試してみたけど変わらず、、


```
ERROR in ./node_modules/@react-native-firebase/app/lib/internal/SharedEventEmitter.js:18
Module not found: Can't resolve 'react-native/Libraries/vendor/emitter/EventEmitter'
  16 |  */
  17 |
> 18 | import EventEmitter from 'react-native/Libraries/vendor/emitter/EventEmitter';
  19 |
  20 | export default new EventEmitter();
  21 |
```

**Comment by Ayato-kosaka** [comment]
あー、node か expo-cli が原因な気がしてきた

**Comment by Ayato-kosaka** [comment]
元々
node: v16.20.0
npm: 8.19.4
expo: 6.3.10

■ node 上げてみる
```
npm install -g n
n latest
```
→ v21.2.0
→ 変わらず

■ npm を上げてみる
```
npm install -g npm@latest
```
→ 10.2.4
→ 変わらず

■ node_modules を削除→更新してみる
→ 変わらず

**Comment by Ayato-kosaka** [comment]
だめだ、よくわかんねぇ〜
環境差異なんだろうけど、解決策がわからんなぁ〜

**Comment by Ayato-kosaka** [comment]
だめだ、GithubActions も落ちるから何か設定が必要そう。。なんで Gitpod は動くんだろ
https://github.com/Ayato-kosaka/spelieve/actions/runs/6993778610/job/19026802333

**Comment by Takapy1** [comment]
@Ayato-kosaka 
この問題想像以上に根深いなー

**Comment by Ayato-kosaka** [comment]
あ、間違えた、、
Gitpod でも動かなったわ、、
ブランチ間違えてた、

**Comment by Ayato-kosaka** [comment]
```
Google Api Error: Invalid request - Your app targets Android 13 (API 33) or above. You must declare the use of advertising ID in Play Console. - Retrying...

```
のエラーが出るなぁ、広告IDを宣言しないといけないみたい、

**Comment by Ayato-kosaka** [comment]
# アプリコンテンツの申告
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/6b13919a-c265-4026-9948-3d1e15ef33f7)
ここから、「金融取引機能」「広告 ID」の申告を行った。
これで、上記のエラーは消えるはず。
結果が出次第再リリース予定

**Comment by Ayato-kosaka** [comment]
@Takapy1 
これって、申請が承認されたメール来たか確認をお願いしてもいい？
俺には来てないっぽくて、でも完了してるっぽいから、承認されたのか承認不要だったのか切り分けしたく。

**Comment by Ayato-kosaka** [comment]
とりあえず完了してるように見えるから以下流してみる。（GitHub Actions 通してないのでもちろん後で取り下げる）
`npx eas-cli build --platform android --auto-submit`

**Comment by Ayato-kosaka** [comment]
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/9f2f779e-c30f-462b-a5aa-b1fd8a9e2f0a)
多分問題なさそう！
Github Actions 流して上手く行けば、

https://github.com/Ayato-kosaka/spelieve/issues/870#issuecomment-1837003535
この回答もらってからクローズする

**Comment by Ayato-kosaka** [comment]
野口もGooglePlay からメールは来ていない。
そもそも二人共メール何も来てなさそう
